// Code generated. DO NOT EDIT.
package v3

import (
	"encoding/json"
	"time"
)

type LocationCountryEnum string

const (
	LocationCountryUS LocationCountryEnum = "US"
	LocationCountryCA                     = "CA"
	LocationCountryMX                     = "MX"
	LocationCountryAF                     = "AF"
	LocationCountryAX                     = "AX"
	LocationCountryAL                     = "AL"
	LocationCountryDZ                     = "DZ"
	LocationCountryAS                     = "AS"
	LocationCountryAD                     = "AD"
	LocationCountryAO                     = "AO"
	LocationCountryAI                     = "AI"
	LocationCountryAQ                     = "AQ"
	LocationCountryAG                     = "AG"
	LocationCountryAR                     = "AR"
	LocationCountryAM                     = "AM"
	LocationCountryAW                     = "AW"
	LocationCountryAU                     = "AU"
	LocationCountryAT                     = "AT"
	LocationCountryAZ                     = "AZ"
	LocationCountryBS                     = "BS"
	LocationCountryBH                     = "BH"
	LocationCountryBD                     = "BD"
	LocationCountryBB                     = "BB"
	LocationCountryBY                     = "BY"
	LocationCountryBE                     = "BE"
	LocationCountryBZ                     = "BZ"
	LocationCountryBJ                     = "BJ"
	LocationCountryBM                     = "BM"
	LocationCountryBT                     = "BT"
	LocationCountryBO                     = "BO"
	LocationCountryBQ                     = "BQ"
	LocationCountryBA                     = "BA"
	LocationCountryBW                     = "BW"
	LocationCountryBV                     = "BV"
	LocationCountryBR                     = "BR"
	LocationCountryIO                     = "IO"
	LocationCountryVG                     = "VG"
	LocationCountryBN                     = "BN"
	LocationCountryBG                     = "BG"
	LocationCountryBF                     = "BF"
	LocationCountryBI                     = "BI"
	LocationCountryCV                     = "CV"
	LocationCountryKH                     = "KH"
	LocationCountryCM                     = "CM"
	LocationCountryKY                     = "KY"
	LocationCountryCF                     = "CF"
	LocationCountryTD                     = "TD"
	LocationCountryCL                     = "CL"
	LocationCountryCN                     = "CN"
	LocationCountryHK                     = "HK"
	LocationCountryMO                     = "MO"
	LocationCountryCX                     = "CX"
	LocationCountryCC                     = "CC"
	LocationCountryCO                     = "CO"
	LocationCountryKM                     = "KM"
	LocationCountryCG                     = "CG"
	LocationCountryCK                     = "CK"
	LocationCountryCR                     = "CR"
	LocationCountryHR                     = "HR"
	LocationCountryCU                     = "CU"
	LocationCountryCW                     = "CW"
	LocationCountryCY                     = "CY"
	LocationCountryCZ                     = "CZ"
	LocationCountryCI                     = "CI"
	LocationCountryKP                     = "KP"
	LocationCountryCD                     = "CD"
	LocationCountryDK                     = "DK"
	LocationCountryDJ                     = "DJ"
	LocationCountryDM                     = "DM"
	LocationCountryDO                     = "DO"
	LocationCountryEC                     = "EC"
	LocationCountryEG                     = "EG"
	LocationCountrySV                     = "SV"
	LocationCountryGQ                     = "GQ"
	LocationCountryER                     = "ER"
	LocationCountryEE                     = "EE"
	LocationCountrySZ                     = "SZ"
	LocationCountryET                     = "ET"
	LocationCountryFK                     = "FK"
	LocationCountryFO                     = "FO"
	LocationCountryFJ                     = "FJ"
	LocationCountryFI                     = "FI"
	LocationCountryFR                     = "FR"
	LocationCountryGF                     = "GF"
	LocationCountryPF                     = "PF"
	LocationCountryTF                     = "TF"
	LocationCountryGA                     = "GA"
	LocationCountryGM                     = "GM"
	LocationCountryGE                     = "GE"
	LocationCountryDE                     = "DE"
	LocationCountryGH                     = "GH"
	LocationCountryGI                     = "GI"
	LocationCountryGR                     = "GR"
	LocationCountryGL                     = "GL"
	LocationCountryGD                     = "GD"
	LocationCountryGP                     = "GP"
	LocationCountryGU                     = "GU"
	LocationCountryGT                     = "GT"
	LocationCountryGG                     = "GG"
	LocationCountryGN                     = "GN"
	LocationCountryGW                     = "GW"
	LocationCountryGY                     = "GY"
	LocationCountryHT                     = "HT"
	LocationCountryHM                     = "HM"
	LocationCountryVA                     = "VA"
	LocationCountryHN                     = "HN"
	LocationCountryHU                     = "HU"
	LocationCountryIS                     = "IS"
	LocationCountryIN                     = "IN"
	LocationCountryID                     = "ID"
	LocationCountryIR                     = "IR"
	LocationCountryIQ                     = "IQ"
	LocationCountryIE                     = "IE"
	LocationCountryIM                     = "IM"
	LocationCountryIL                     = "IL"
	LocationCountryIT                     = "IT"
	LocationCountryJM                     = "JM"
	LocationCountryJP                     = "JP"
	LocationCountryJE                     = "JE"
	LocationCountryJO                     = "JO"
	LocationCountryKZ                     = "KZ"
	LocationCountryKE                     = "KE"
	LocationCountryKI                     = "KI"
	LocationCountryKW                     = "KW"
	LocationCountryKG                     = "KG"
	LocationCountryLA                     = "LA"
	LocationCountryLV                     = "LV"
	LocationCountryLB                     = "LB"
	LocationCountryLS                     = "LS"
	LocationCountryLR                     = "LR"
	LocationCountryLY                     = "LY"
	LocationCountryLI                     = "LI"
	LocationCountryLT                     = "LT"
	LocationCountryLU                     = "LU"
	LocationCountryMG                     = "MG"
	LocationCountryMW                     = "MW"
	LocationCountryMY                     = "MY"
	LocationCountryMV                     = "MV"
	LocationCountryML                     = "ML"
	LocationCountryMT                     = "MT"
	LocationCountryMH                     = "MH"
	LocationCountryMQ                     = "MQ"
	LocationCountryMR                     = "MR"
	LocationCountryMU                     = "MU"
	LocationCountryYT                     = "YT"
	LocationCountryFM                     = "FM"
	LocationCountryMC                     = "MC"
	LocationCountryMN                     = "MN"
	LocationCountryME                     = "ME"
	LocationCountryMS                     = "MS"
	LocationCountryMA                     = "MA"
	LocationCountryMZ                     = "MZ"
	LocationCountryMM                     = "MM"
	LocationCountryNA                     = "NA"
	LocationCountryNR                     = "NR"
	LocationCountryNP                     = "NP"
	LocationCountryNL                     = "NL"
	LocationCountryNC                     = "NC"
	LocationCountryNZ                     = "NZ"
	LocationCountryNI                     = "NI"
	LocationCountryNE                     = "NE"
	LocationCountryNG                     = "NG"
	LocationCountryNU                     = "NU"
	LocationCountryNF                     = "NF"
	LocationCountryMP                     = "MP"
	LocationCountryNO                     = "NO"
	LocationCountryOM                     = "OM"
	LocationCountryPK                     = "PK"
	LocationCountryPW                     = "PW"
	LocationCountryPA                     = "PA"
	LocationCountryPG                     = "PG"
	LocationCountryPY                     = "PY"
	LocationCountryPE                     = "PE"
	LocationCountryPH                     = "PH"
	LocationCountryPN                     = "PN"
	LocationCountryPL                     = "PL"
	LocationCountryPT                     = "PT"
	LocationCountryPR                     = "PR"
	LocationCountryQA                     = "QA"
	LocationCountryKR                     = "KR"
	LocationCountryMD                     = "MD"
	LocationCountryRO                     = "RO"
	LocationCountryRU                     = "RU"
	LocationCountryRW                     = "RW"
	LocationCountryRE                     = "RE"
	LocationCountryBL                     = "BL"
	LocationCountrySH                     = "SH"
	LocationCountryKN                     = "KN"
	LocationCountryLC                     = "LC"
	LocationCountryMF                     = "MF"
	LocationCountryPM                     = "PM"
	LocationCountryVC                     = "VC"
	LocationCountryWS                     = "WS"
	LocationCountrySM                     = "SM"
	LocationCountryST                     = "ST"
	LocationCountrySA                     = "SA"
	LocationCountrySN                     = "SN"
	LocationCountryRS                     = "RS"
	LocationCountrySC                     = "SC"
	LocationCountrySL                     = "SL"
	LocationCountrySG                     = "SG"
	LocationCountrySX                     = "SX"
	LocationCountrySK                     = "SK"
	LocationCountrySI                     = "SI"
	LocationCountrySB                     = "SB"
	LocationCountrySO                     = "SO"
	LocationCountryZA                     = "ZA"
	LocationCountryGS                     = "GS"
	LocationCountrySS                     = "SS"
	LocationCountryES                     = "ES"
	LocationCountryLK                     = "LK"
	LocationCountryPS                     = "PS"
	LocationCountrySD                     = "SD"
	LocationCountrySR                     = "SR"
	LocationCountrySJ                     = "SJ"
	LocationCountrySE                     = "SE"
	LocationCountryCH                     = "CH"
	LocationCountrySY                     = "SY"
	LocationCountryTW                     = "TW"
	LocationCountryTJ                     = "TJ"
	LocationCountryTH                     = "TH"
	LocationCountryMK                     = "MK"
	LocationCountryTL                     = "TL"
	LocationCountryTG                     = "TG"
	LocationCountryTK                     = "TK"
	LocationCountryTO                     = "TO"
	LocationCountryTT                     = "TT"
	LocationCountryTN                     = "TN"
	LocationCountryTR                     = "TR"
	LocationCountryTM                     = "TM"
	LocationCountryTC                     = "TC"
	LocationCountryTV                     = "TV"
	LocationCountryUG                     = "UG"
	LocationCountryUA                     = "UA"
	LocationCountryAE                     = "AE"
	LocationCountryGB                     = "GB"
	LocationCountryTZ                     = "TZ"
	LocationCountryUM                     = "UM"
	LocationCountryVI                     = "VI"
	LocationCountryUY                     = "UY"
	LocationCountryUZ                     = "UZ"
	LocationCountryVU                     = "VU"
	LocationCountryVE                     = "VE"
	LocationCountryVN                     = "VN"
	LocationCountryWF                     = "WF"
	LocationCountryEH                     = "EH"
	LocationCountryYE                     = "YE"
	LocationCountryZM                     = "ZM"
	LocationCountryZW                     = "ZW"
)

type Location struct {
	Address1              string              `gorm:"not null" json:"address1"`
	ID                    string              `gorm:"primaryKey;not null" json:"id"`
	Address2              *string             `json:"address2"`
	City                  string              `gorm:"not null" json:"city"`
	CompanyId             string              `gorm:"not null" json:"companyId"`
	ContactName           *string             `json:"contactName"` // the location contact name
	Country               LocationCountryEnum `gorm:"not null" json:"country"`
	CreatedDate           time.Time           `gorm:"column:createdDate;not null" json:"createdDate"`
	Email                 *string             `json:"email"`                                                       // the location email for generic inqueries
	LocationPhoneNumberId *string             `json:"locationPhoneNumberId"`                                       // the location phone number
	Meta                  *Meta               `gorm:"embedded;column:meta;not null" json:"meta,omitempty"`         // the metadata about the most recent change to the row
	Metadata              any                 `gorm:"embedded;column:metadata;not null" json:"metadata,omitempty"` // metadata reserved for customers to control
	Name                  string              `gorm:"not null" json:"name"`
	PostalCode            string              `gorm:"not null" json:"postalCode"`
	State                 string              `gorm:"not null" json:"state"`
	Timezone              string              `gorm:"not null" json:"timezone"`
	UpdatedDate           *time.Time          `gorm:"column:updatedDate" json:"updatedDate"`
	Website               *string             `json:"website"`
}

// TableName returns the name of the table for this model which GORM will use when using this model
func (m *Location) TableName() string {
	return "location"
}

func (m *Location) String() string {
	buf, _ := json.Marshal(m)
	return string(buf)
}
