// Code generated. DO NOT EDIT.
package v3

import (
	"encoding/json"
	"time"
)

type VendorCountryEnum string

const (
	VendorCountryUS VendorCountryEnum = "US"
	VendorCountryCA                   = "CA"
	VendorCountryMX                   = "MX"
	VendorCountryAF                   = "AF"
	VendorCountryAX                   = "AX"
	VendorCountryAL                   = "AL"
	VendorCountryDZ                   = "DZ"
	VendorCountryAS                   = "AS"
	VendorCountryAD                   = "AD"
	VendorCountryAO                   = "AO"
	VendorCountryAI                   = "AI"
	VendorCountryAQ                   = "AQ"
	VendorCountryAG                   = "AG"
	VendorCountryAR                   = "AR"
	VendorCountryAM                   = "AM"
	VendorCountryAW                   = "AW"
	VendorCountryAU                   = "AU"
	VendorCountryAT                   = "AT"
	VendorCountryAZ                   = "AZ"
	VendorCountryBS                   = "BS"
	VendorCountryBH                   = "BH"
	VendorCountryBD                   = "BD"
	VendorCountryBB                   = "BB"
	VendorCountryBY                   = "BY"
	VendorCountryBE                   = "BE"
	VendorCountryBZ                   = "BZ"
	VendorCountryBJ                   = "BJ"
	VendorCountryBM                   = "BM"
	VendorCountryBT                   = "BT"
	VendorCountryBO                   = "BO"
	VendorCountryBQ                   = "BQ"
	VendorCountryBA                   = "BA"
	VendorCountryBW                   = "BW"
	VendorCountryBV                   = "BV"
	VendorCountryBR                   = "BR"
	VendorCountryIO                   = "IO"
	VendorCountryVG                   = "VG"
	VendorCountryBN                   = "BN"
	VendorCountryBG                   = "BG"
	VendorCountryBF                   = "BF"
	VendorCountryBI                   = "BI"
	VendorCountryCV                   = "CV"
	VendorCountryKH                   = "KH"
	VendorCountryCM                   = "CM"
	VendorCountryKY                   = "KY"
	VendorCountryCF                   = "CF"
	VendorCountryTD                   = "TD"
	VendorCountryCL                   = "CL"
	VendorCountryCN                   = "CN"
	VendorCountryHK                   = "HK"
	VendorCountryMO                   = "MO"
	VendorCountryCX                   = "CX"
	VendorCountryCC                   = "CC"
	VendorCountryCO                   = "CO"
	VendorCountryKM                   = "KM"
	VendorCountryCG                   = "CG"
	VendorCountryCK                   = "CK"
	VendorCountryCR                   = "CR"
	VendorCountryHR                   = "HR"
	VendorCountryCU                   = "CU"
	VendorCountryCW                   = "CW"
	VendorCountryCY                   = "CY"
	VendorCountryCZ                   = "CZ"
	VendorCountryCI                   = "CI"
	VendorCountryKP                   = "KP"
	VendorCountryCD                   = "CD"
	VendorCountryDK                   = "DK"
	VendorCountryDJ                   = "DJ"
	VendorCountryDM                   = "DM"
	VendorCountryDO                   = "DO"
	VendorCountryEC                   = "EC"
	VendorCountryEG                   = "EG"
	VendorCountrySV                   = "SV"
	VendorCountryGQ                   = "GQ"
	VendorCountryER                   = "ER"
	VendorCountryEE                   = "EE"
	VendorCountrySZ                   = "SZ"
	VendorCountryET                   = "ET"
	VendorCountryFK                   = "FK"
	VendorCountryFO                   = "FO"
	VendorCountryFJ                   = "FJ"
	VendorCountryFI                   = "FI"
	VendorCountryFR                   = "FR"
	VendorCountryGF                   = "GF"
	VendorCountryPF                   = "PF"
	VendorCountryTF                   = "TF"
	VendorCountryGA                   = "GA"
	VendorCountryGM                   = "GM"
	VendorCountryGE                   = "GE"
	VendorCountryDE                   = "DE"
	VendorCountryGH                   = "GH"
	VendorCountryGI                   = "GI"
	VendorCountryGR                   = "GR"
	VendorCountryGL                   = "GL"
	VendorCountryGD                   = "GD"
	VendorCountryGP                   = "GP"
	VendorCountryGU                   = "GU"
	VendorCountryGT                   = "GT"
	VendorCountryGG                   = "GG"
	VendorCountryGN                   = "GN"
	VendorCountryGW                   = "GW"
	VendorCountryGY                   = "GY"
	VendorCountryHT                   = "HT"
	VendorCountryHM                   = "HM"
	VendorCountryVA                   = "VA"
	VendorCountryHN                   = "HN"
	VendorCountryHU                   = "HU"
	VendorCountryIS                   = "IS"
	VendorCountryIN                   = "IN"
	VendorCountryID                   = "ID"
	VendorCountryIR                   = "IR"
	VendorCountryIQ                   = "IQ"
	VendorCountryIE                   = "IE"
	VendorCountryIM                   = "IM"
	VendorCountryIL                   = "IL"
	VendorCountryIT                   = "IT"
	VendorCountryJM                   = "JM"
	VendorCountryJP                   = "JP"
	VendorCountryJE                   = "JE"
	VendorCountryJO                   = "JO"
	VendorCountryKZ                   = "KZ"
	VendorCountryKE                   = "KE"
	VendorCountryKI                   = "KI"
	VendorCountryKW                   = "KW"
	VendorCountryKG                   = "KG"
	VendorCountryLA                   = "LA"
	VendorCountryLV                   = "LV"
	VendorCountryLB                   = "LB"
	VendorCountryLS                   = "LS"
	VendorCountryLR                   = "LR"
	VendorCountryLY                   = "LY"
	VendorCountryLI                   = "LI"
	VendorCountryLT                   = "LT"
	VendorCountryLU                   = "LU"
	VendorCountryMG                   = "MG"
	VendorCountryMW                   = "MW"
	VendorCountryMY                   = "MY"
	VendorCountryMV                   = "MV"
	VendorCountryML                   = "ML"
	VendorCountryMT                   = "MT"
	VendorCountryMH                   = "MH"
	VendorCountryMQ                   = "MQ"
	VendorCountryMR                   = "MR"
	VendorCountryMU                   = "MU"
	VendorCountryYT                   = "YT"
	VendorCountryFM                   = "FM"
	VendorCountryMC                   = "MC"
	VendorCountryMN                   = "MN"
	VendorCountryME                   = "ME"
	VendorCountryMS                   = "MS"
	VendorCountryMA                   = "MA"
	VendorCountryMZ                   = "MZ"
	VendorCountryMM                   = "MM"
	VendorCountryNA                   = "NA"
	VendorCountryNR                   = "NR"
	VendorCountryNP                   = "NP"
	VendorCountryNL                   = "NL"
	VendorCountryNC                   = "NC"
	VendorCountryNZ                   = "NZ"
	VendorCountryNI                   = "NI"
	VendorCountryNE                   = "NE"
	VendorCountryNG                   = "NG"
	VendorCountryNU                   = "NU"
	VendorCountryNF                   = "NF"
	VendorCountryMP                   = "MP"
	VendorCountryNO                   = "NO"
	VendorCountryOM                   = "OM"
	VendorCountryPK                   = "PK"
	VendorCountryPW                   = "PW"
	VendorCountryPA                   = "PA"
	VendorCountryPG                   = "PG"
	VendorCountryPY                   = "PY"
	VendorCountryPE                   = "PE"
	VendorCountryPH                   = "PH"
	VendorCountryPN                   = "PN"
	VendorCountryPL                   = "PL"
	VendorCountryPT                   = "PT"
	VendorCountryPR                   = "PR"
	VendorCountryQA                   = "QA"
	VendorCountryKR                   = "KR"
	VendorCountryMD                   = "MD"
	VendorCountryRO                   = "RO"
	VendorCountryRU                   = "RU"
	VendorCountryRW                   = "RW"
	VendorCountryRE                   = "RE"
	VendorCountryBL                   = "BL"
	VendorCountrySH                   = "SH"
	VendorCountryKN                   = "KN"
	VendorCountryLC                   = "LC"
	VendorCountryMF                   = "MF"
	VendorCountryPM                   = "PM"
	VendorCountryVC                   = "VC"
	VendorCountryWS                   = "WS"
	VendorCountrySM                   = "SM"
	VendorCountryST                   = "ST"
	VendorCountrySA                   = "SA"
	VendorCountrySN                   = "SN"
	VendorCountryRS                   = "RS"
	VendorCountrySC                   = "SC"
	VendorCountrySL                   = "SL"
	VendorCountrySG                   = "SG"
	VendorCountrySX                   = "SX"
	VendorCountrySK                   = "SK"
	VendorCountrySI                   = "SI"
	VendorCountrySB                   = "SB"
	VendorCountrySO                   = "SO"
	VendorCountryZA                   = "ZA"
	VendorCountryGS                   = "GS"
	VendorCountrySS                   = "SS"
	VendorCountryES                   = "ES"
	VendorCountryLK                   = "LK"
	VendorCountryPS                   = "PS"
	VendorCountrySD                   = "SD"
	VendorCountrySR                   = "SR"
	VendorCountrySJ                   = "SJ"
	VendorCountrySE                   = "SE"
	VendorCountryCH                   = "CH"
	VendorCountrySY                   = "SY"
	VendorCountryTW                   = "TW"
	VendorCountryTJ                   = "TJ"
	VendorCountryTH                   = "TH"
	VendorCountryMK                   = "MK"
	VendorCountryTL                   = "TL"
	VendorCountryTG                   = "TG"
	VendorCountryTK                   = "TK"
	VendorCountryTO                   = "TO"
	VendorCountryTT                   = "TT"
	VendorCountryTN                   = "TN"
	VendorCountryTR                   = "TR"
	VendorCountryTM                   = "TM"
	VendorCountryTC                   = "TC"
	VendorCountryTV                   = "TV"
	VendorCountryUG                   = "UG"
	VendorCountryUA                   = "UA"
	VendorCountryAE                   = "AE"
	VendorCountryGB                   = "GB"
	VendorCountryTZ                   = "TZ"
	VendorCountryUM                   = "UM"
	VendorCountryVI                   = "VI"
	VendorCountryUY                   = "UY"
	VendorCountryUZ                   = "UZ"
	VendorCountryVU                   = "VU"
	VendorCountryVE                   = "VE"
	VendorCountryVN                   = "VN"
	VendorCountryWF                   = "WF"
	VendorCountryEH                   = "EH"
	VendorCountryYE                   = "YE"
	VendorCountryZM                   = "ZM"
	VendorCountryZW                   = "ZW"
)

type Vendor struct {
	ID               string             `gorm:"primaryKey;not null" json:"id"`
	AccountNumber    *string            `json:"accountNumber"`
	Address1         *string            `json:"address1"`
	Address2         *string            `json:"address2"`
	City             *string            `json:"city"`
	CompanyId        string             `gorm:"not null" json:"companyId"`
	ContactEmail     *string            `json:"contactEmail"`
	ContactFirstName *string            `json:"contactFirstName"`
	ContactLastName  *string            `json:"contactLastName"`
	ContactPhone     any                `gorm:"not null" json:"contactPhone"`
	Country          *VendorCountryEnum `json:"country"`
	CreatedDate      time.Time          `gorm:"column:createdDate;not null" json:"createdDate"`
	LocationId       string             `gorm:"not null" json:"locationId"`
	Meta             *Meta              `gorm:"embedded;column:meta;not null" json:"meta,omitempty"`         // the metadata about the most recent change to the row
	Metadata         any                `gorm:"embedded;column:metadata;not null" json:"metadata,omitempty"` // metadata reserved for customers to control
	Name             string             `gorm:"not null" json:"name"`
	PostalCode       *string            `json:"postalCode"`
	State            *string            `json:"state"`
	UpdatedDate      *time.Time         `gorm:"column:updatedDate" json:"updatedDate"`
	Url              *string            `json:"url"`
}

// TableName returns the name of the table for this model which GORM will use when using this model
func (m *Vendor) TableName() string {
	return "vendor"
}

func (m *Vendor) String() string {
	buf, _ := json.Marshal(m)
	return string(buf)
}
